### ISSUE TITLE
Hibernate is invalid

### ISSUE THREAD

**Issue by Chalkim** [varlesh/org.kde.plasma.compact-shutdown#1]
### Brief description of bug

Hibernate is invalid

#### Environment
Operating System: Arch Linux
KDE Plasma Version: 5.21.0
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.10.16-arch1-1
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-7300HQ CPU @ 2.50GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

#### Steps to Reproduce the Issue

![Screenshot_20210221_041521](https://user-images.githubusercontent.com/37498010/108607462-904ec900-73fb-11eb-96e2-4a1d7f819d67.png)

Well, click that label and do nothing. I'm sure my laptop can hibernate properly for `$ systemctl hibernate` runs nicely.

**Comment by varlesh** [comment]
it's worked for you with qdbus?
`qdbus org.kde.Solid.PowerManagement /org/freedesktop/PowerManagement Hibernate`

**Comment by Chalkim** [comment]
Yes, qdbus works well too.

**Comment by varlesh** [comment]
ok, thx

**Comment by varlesh** [comment]
fixed

**Comment by varlesh** [comment]
@Chalkim @aConar New version released on KDE Store
