### ISSUE TITLE
Feature Idea: User-Selectable Entries

### ISSUE THREAD

**Issue by Forger125** [varlesh/org.kde.plasma.compact-shutdown#10]
First and foremost @varlesh , thanks so much for a clean, useful plasmoid! Use it on all of my KDE machines and appreciate your work on it. Just wanted to throw out an idea that I think would make the plasmoid even more refined, and that is the ability to customize what's in the menu. The use case of this is that some users might not ever plan on using / set up some of the power menu functions, e.g. hibernate. 

In the plasma widget configuration screen, maybe it would be possible to have a checklist-style selection screen where you can pick what is in the widget, i.e. unchecking hibernate --> hibernate does not appear in the list displayed by the widget? Potentially, in the future, maybe have the user be able to add an entry which executes an arbitrary command?

Either way, thanks for your work on this and appreciate your contribution to the Kommunity! :)

**Comment by varlesh** [comment]
added
![image](https://user-images.githubusercontent.com/8083855/123896807-51192180-d973-11eb-9f1d-0e91edddc921.png)

**Comment by Forger125** [comment]
Amazing! Thank you for being so receptive and responsive @varlesh - awesome!!! :smiley:
