### ISSUE TITLE
Wrong translation PL

### ISSUE THREAD

**Issue by Plazmin** [varlesh/org.kde.plasma.compact-shutdown#13]
**Should be:**

msgid "Logout"
msgstr "Wyloguj"

msgid "Suspend"
msgstr "Uśpij"

msgid "Hibernate"
msgstr "Zahibernuj"

msgid "Reboot"
msgstr "Uruchom ponownie"

msgid "Shutdown"
msgstr "Wyłącz"

msgid "Lock Screen"
msgstr "Zablokuj"

msgid "Appearance"
msgstr "Wygląd"

msgid "Show buttons:"
msgstr "Pokaż przyciski:"

This is according to the official translation KDE.

**Comment by varlesh** [comment]
thx, updated
