### ISSUE TITLE
No action when clicked

### ISSUE THREAD

**Issue by Roknauta** [varlesh/org.kde.plasma.compact-shutdown#14]
I added the widget but no action when clicked on any option.

![2021-12-07_08-41](https://user-images.githubusercontent.com/7780234/145027374-5d70962e-a01e-42e4-8cb6-a89128c9f18f.png)

OS information: 

Operating System: Arch Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.5-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700 Eight-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2

**Comment by varlesh** [comment]
This widget use qdbus, you are install `qt5-tools` package?
This command worked from Konsole?:
`qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock`

**Comment by Roknauta** [comment]
> 

Nice, solved...thanks a lot.
