### ISSUE TITLE
Compact Shutdown stopped working after upgrading from Fedora 35 to 36

### ISSUE THREAD

**Issue by Chaz6** [varlesh/org.kde.plasma.compact-shutdown#16]
After upgrading to Fedora 36, the widget no longer works. I can see it on my desktop, but clicking does nothing. What information can I provide to help debug this?

**Comment by Chaz6** [comment]
I see now my link to `qdbus` was removed. I made a new link from `$HOME/.local/bin/qdbus` to `/usr/bin/qdbus-qt5` and now it works!

**Comment by varlesh** [comment]
Similar issue with OpenSuse... I dont't know why developers rename qdbus
https://github.com/varlesh/org.kde.plasma.compact-shutdown/issues/8

**Comment by OnkarRuikar** [comment]
On `Fedora 36 5.18.13-200.fc36.x86_64` I had to do following to get it working:
```bash
cd /usr/bin
sudo ln -s qdbus-qt5 qdbus
```
