### ISSUE TITLE
Not work correctly.

### ISSUE THREAD

**Issue by Plazmin** [varlesh/org.kde.plasma.compact-shutdown#19]
Debian bullseye last upgrade.
![CS](https://user-images.githubusercontent.com/62091912/176642135-e6ab8268-0224-4c59-968c-4d43cf691d03.png)

**Comment by varlesh** [comment]
Your plasma-framework package old... i can't support multiple systems.
https://github.com/KDE/plasma-framework/commit/734b956c27bd76df7fed6979beb27c2f30cbd3bf
But i think it's can be solved for you. Need only comment out a line `hovered: true`  in the code **main.qml**:
```
PlasmaComponents.Highlight {
        id: delegateHighlight
        visible: false
//         hovered: true
        z: -1 // otherwise it shows ontop of the icon/label and tints them slightly
    }
```

**Comment by Plazmin** [comment]
I thought the problem was related to Compact Shutdown. I've done a fix in main.qml before and everything is back to normal. I'm closing the issue.

**Comment by varlesh** [comment]
Ok. I'm already added 2 versions on KDE Store
