### ISSUE TITLE
Widget Not Fitting Properly

### ISSUE THREAD

**Issue by Godly-Avenger** [varlesh/org.kde.plasma.compact-shutdown#21]
The attached image shows that the widget's options get cut off. My screens resolution is 4k (technically 3840x1887 since I'm using a VM) and my dpi is 96 dpi. My zoom is set to 200% and I'm using Kali Linux on a VirtualBox VM if that information helps. Thanks!

![image](https://user-images.githubusercontent.com/74989919/179394480-6d34e289-1ab6-482c-a3b3-58ce83144487.png)

**Comment by varlesh** [comment]
You can change size here:
https://github.com/varlesh/org.kde.plasma.compact-shutdown/blob/main/contents/ui/main.qml#L90-L91
For example, set 300. Then restart plasma.

**Comment by varlesh** [comment]
it's located here `~/.local/share/plasma/plasmoids/org.kde.plasma.compact-shutdown/contents/ui/main.qml`

**Comment by Godly-Avenger** [comment]
Thank you so much! Doubling it made it work perfectly.

**Comment by varlesh** [comment]
@Godly-Avenger I'm added Size option on Configuration
