### ISSUE TITLE
Adjust applet size

### ISSUE THREAD

**Issue by aConar** [varlesh/org.kde.plasma.compact-shutdown#6]
Some cosmetic issues. Some options are not visible and some names are not complete. They are covered by the panel:
![plasmoid](https://user-images.githubusercontent.com/4622888/109406895-76613900-795b-11eb-8d00-9627280d6290.png)

**Comment by varlesh** [comment]
you use 4K or another DPI?

**Comment by varlesh** [comment]
I'm change applet size to 180x180. Try it

**Comment by varlesh** [comment]
on FullHD 1080p and default DPI: 96 it's look like this:
![image](https://user-images.githubusercontent.com/8083855/109409523-f499fb80-79ac-11eb-8aeb-eb22915bb678.png)

**Comment by aConar** [comment]
Works perfect! Thanks!
![image](https://user-images.githubusercontent.com/4622888/109418925-87389b80-79a9-11eb-8537-b6cfc4326f54.png)
