### ISSUE TITLE
Doesn't work in opensuse tumbleweed 

### ISSUE THREAD

**Issue by heybam** [varlesh/org.kde.plasma.compact-shutdown#8]
Hi Varlesh!
All buttons are not working in opensuse tumbleweed. Below are my system details.
`OS: Opensuse Tumbleweed 20210321`
`Plasma Version: 5.21.3`
`Framework Version: 5.80`

**Comment by varlesh** [comment]
This widget use qdbus. You install this package?

**Comment by heybam** [comment]
did you mean "libqt5-qdbus", sir? if yes, yeah i have the package installed.

**Comment by varlesh** [comment]
Opensuse use `qdbus-qt5` command. Temporarry solution - create symlink:
`sudo ln -s ../lib64/qt5/bin/qdbus /usr/bin/qdbus`

**Comment by heybam** [comment]
awesome! it works amazingly now
thank you sir!
